{{- if .Values.collectors.cluster.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "superlog-otel.componentName" (dict "root" . "component" "cluster") }}
  labels:
    {{- include "superlog-otel.labels" . | nindent 4 }}
    app.kubernetes.io/component: cluster
data:
  relay: |
    {{- .Files.Get "files/cluster.yaml" | nindent 4 }}
{{- end }}
