{{- if or .Values.collectors.agent.enabled .Values.collectors.cluster.enabled }}
{{- if not .Values.global.superlog.existingSecret.name }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "superlog-otel.authSecretName" . }}
  labels:
    {{- include "superlog-otel.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.global.superlog.existingSecret.key | quote }}: {{ required "global.superlog.apiKey or global.superlog.existingSecret.name is required" .Values.global.superlog.apiKey | quote }}
{{- end }}
{{- end }}
