{{- if .Values.collectors.agent.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "superlog-otel.componentName" (dict "root" . "component" "agent") }}
  labels:
    {{- include "superlog-otel.labels" . | nindent 4 }}
    app.kubernetes.io/component: agent
automountServiceAccountToken: true
---
{{- end }}
{{- if .Values.collectors.cluster.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "superlog-otel.componentName" (dict "root" . "component" "cluster") }}
  labels:
    {{- include "superlog-otel.labels" . | nindent 4 }}
    app.kubernetes.io/component: cluster
automountServiceAccountToken: true
{{- end }}

